"""Render measured quality, latency, verification work and sampler diagnostics."""
import csv
import json
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent


def main():
    metrics = json.loads((ROOT/"runs/metrics.json").read_text())
    bench = json.loads((ROOT/"runs/benchmark.json").read_text())
    sampler = json.loads((ROOT/"runs/sampler_check.json").read_text())
    with (ROOT/"runs/training_history.csv").open() as handle:
        history = list(csv.DictReader(handle))
    destination = ROOT/"figures"
    destination.mkdir(exist_ok=True)
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 11, "axes.spines.top": False,
                         "axes.spines.right": False, "figure.dpi": 150, "savefig.dpi": 170})
    colors = {"draft": "#c37d23", "target": "#2457a6"}
    def save(fig, name):
        fig.savefig(destination/f"{name}.png", bbox_inches="tight", facecolor="white")
        plt.close(fig)
    fig, ax = plt.subplots(figsize=(8, 4.8), layout="constrained")
    for role in colors:
        rows = [r for r in history if r["model"] == role]
        ax.plot([int(r["step"]) for r in rows], [float(r["validation_nll"]) for r in rows], marker="o", label=role.title(), color=colors[role])
    ax.set(xlabel="Optimizer step", ylabel="Validation NLL (nats / byte)", title="Same sampled windows; different model capacity")
    ax.legend()
    ax.grid(alpha=.2)
    save(fig, "training-curves")
    fig, ax = plt.subplots(figsize=(8, 4.8), layout="constrained")
    labels = ["Unigram", "Draft", "Target"]
    values = [metrics["unigram"]["test_perplexity"], *[metrics["models"][role]["test"]["perplexity"] for role in colors]]
    bars = ax.bar(labels, values, color=["#7b8794", *colors.values()], width=.6)
    ax.bar_label(bars, labels=[f"{v:.2f}" for v in values], padding=4)
    ax.set(ylim=(0, max(values)*1.18), ylabel="Byte perplexity (lower is better)", title="Final contiguous holdout: 15,072 evaluated byte targets")
    save(fig, "model-comparison")
    for name, field, ylabel, title in (("latency", "median_ms", "Request latency (ms)", "48 generated bytes · batch 1 · CPU"),
                                       ("target-calls", "mean_target_calls", "Target forward calls per request", "Fewer target calls can still take longer")):
        fig, axes = plt.subplots(1, 2, figsize=(11, 4.8), layout="constrained")
        for ax, mode in zip(axes, ("greedy", "sample")):
            rows = [r for r in bench["summaries"] if r["mode"] == mode]
            vals = [r[field] for r in rows]
            bars = ax.bar(["Target", "γ=1", "γ=2", "γ=4", "γ=8"], vals, color=["#7b8794", "#77a9db", "#548ac6", "#326daf", "#2457a6"])
            ax.bar_label(bars, labels=[f"{v:.1f}" for v in vals], padding=3, zorder=5,
                         bbox={"facecolor": "white", "edgecolor": "none", "pad": 1})
            if name == "latency":
                upper = [r["p95_ms"]-r["median_ms"] for r in rows]
                ax.errorbar(np.arange(5), vals, yerr=np.array([np.zeros(5), upper]), fmt="none", color="#263442", capsize=3)
                ax.set_ylim(0, max(r["p95_ms"] for r in rows)*1.2)
            else:
                ax.set_ylim(0, max(vals)*1.2)
            ax.set(title=mode.title(), ylabel=ylabel)
        fig.suptitle(title+("\nBars: median · whiskers: p95 · 48 requests per variant" if name == "latency" else ""))
        save(fig, name)
    fig, ax = plt.subplots(figsize=(8, 4.8), layout="constrained")
    for mode, color in (("greedy", "#2457a6"), ("sample", "#c37d23")):
        rows = [r for r in bench["summaries"] if r["mode"] == mode and r["variant"] != "reference"]
        ax.plot([1, 2, 4, 8], [r["acceptance_fraction"] for r in rows], marker="o", label=mode.title(), color=color)
    ax.set(xticks=[1, 2, 4, 8], ylim=(0, 1), xlabel="Draft block size γ", ylabel="Accepted / all proposed tokens", title="Longer blocks also spend work on discarded proposals")
    ax.legend()
    ax.grid(alpha=.2)
    save(fig, "acceptance")
    fig, ax = plt.subplots(figsize=(9, 4.8), layout="constrained")
    x = np.arange(8)
    expected = sampler["expected_joint_probabilities"]
    observed = sampler["observed_joint_frequencies"]
    ax.bar(x-.18, expected, width=.36, label="Exact target joint law", color="#2457a6")
    ax.bar(x+.18, observed, width=.36, label="Corrected speculative frequency", color="#c37d23")
    ax.set(xticks=x, xticklabels=["".join(map(str, s)) for s in sampler["sequences"]], xlabel="Three generated token IDs", ylabel="Probability / frequency", title="History-dependent sampler audit · 12,000 fixed seeds")
    ax.legend()
    save(fig, "distribution-check")


if __name__ == "__main__":
    main()
